version: "2.0"
services:
 java-hibernate:
  build:
   context: .
   dockerfile: Dockerfile
  links:
    - backend
  depends_on:
    - backend
  stdin_open: true # docker run -i
  tty: true
 backend:
   image: mysql:5.7
   restart: always
   environment:
     MYSQL_DATABASE: 'dataset'
      # So you don't have to use root, but you can if you like
     MYSQL_USER: 'username'
      # You can use whatever password you like
     MYSQL_PASSWORD: 'password'
      # Password for root access
     MYSQL_ROOT_PASSWORD: 'password'
   ports:
      - '3306:3306'
